### ISSUE TITLE
"ERROR: ./package/hello/src does not exist" in 53f53d5

### ISSUE THREAD

**Issue by cirosantilli** [cirosantilli/buildroot#1]
Moved from: https://github.com/buildroot/buildroot/compare/master...cirosantilli:in-tree-package-2016.05#commitcomment-26050535

53f53d5 fails with:

```
hello 1.0 Syncing from source dir ./package/hello/src
ERROR: ./package/hello/src does not exist
```

This is the case no matter what valid path is placed in the HELLO_SITE variable, absolute or relative. Any 
idea what's missing?

**Comment by cirosantilli** [comment]
I can't reproduce the error on the tip of the branch https://github.com/cirosantilli/buildroot/tree/in-tree-package-2016.05 at commit https://github.com/cirosantilli/buildroot/commit/7f2c9b3e011aed8202be778efa7479e376f80d01 even though the newer commits appear to do nothing new.

Please ensure that you are running the exact instructions documented on the README of that commit.

I've just tested on Ubuntu 16.04 with a fresh clone.

Let me know if you find something about the error.

**Comment by shefft** [comment]
After further research, it turns out this problem is likely related to the Docker environment.  Please close.  Thank you.

**Comment by cirosantilli** [comment]
OK, glad its solved!
